ProceduralDistributions = {};

ProceduralDistributions.list = {

    EasyPackingItems_counter_medical = {
        rolls = 4,
        items = {
            "GidOrganized.OS12pkAdhesiveBandages", 2,
            "GidOrganized.OS9pkBandages", 2,
            "GidOrganized.OS9pkSterileBandages", 2,
            "GidOrganized.OS12pkCottonBalls", 2,
            "GidOrganized.OS50pkPainkillers", 1,
            "GidOrganized.OS50pkVitamins", 1,
            "GidOrganized.OS50pkBetaBlockers", 1,
            "GidOrganized.OS50pkAntidepressants", 1,
            "GidOrganized.OS50pkSleepingPills", 1,
            "GidOrganized.OS4pkDisinfectant", 2,
            "GidOrganized.OS30pkAlcoholWipes", 1.6,
            "GidOrganized.OS30pkAntibiotics", 0.4,
        }
    },

    EasyPackingItems_metalShelves_medical= {
        rolls = 4,
        items = {
            "GidOrganized.OS12pkAdhesiveBandages", 4,
            "GidOrganized.OS9pkBandages", 4,
            "GidOrganized.OS9pkSterileBandag1,es", 4,
            "GidOrganized.OS12pkCottonBalls", 4,
            "GidOrganized.OS50pkPainkillers", 2,
            "GidOrganized.OS50pkVitamins", 2,
            "GidOrganized.OS50pkBetaBlockers", 2,
            "GidOrganized.OS50pkAntidepressants", 2,
            "GidOrganized.OS50pkSleepingPills", 2,
            "GidOrganized.OS4pkDisinfectant", 4,
            "GidOrganized.OS30pkAlcoholWipes", 3.2,
            "GidOrganized.OS30pkAntibiotics", 1,
        }
    },

    EasyPackingItems_shelves_medical = {
        rolls = 4,
        items = {
            "GidOrganized.OS12pkAdhesiveBandages", 2,
            "GidOrganized.OS9pkBandages", 2,
            "GidOrganized.OS9pkSterileBandages", 2,
            "GidOrganized.OS12pkCottonBcounters", 2,
            "GidOrganized.OS50pkPainkillers", 1,
            "GidOrganized.OS50pkVitamins", 1,
            "GidOrganized.OS50pkBetaBlockers", 1,
            "GidOrganized.OS50pkAntidepressants", 1,
            "GidOrganized.OS50pkSleepingPills", 1,
            "GidOrganized.OS4pkDisinfectant", 2,
            "GidOrganized.OS30pkAlcoholWipes", 1.6,
            "GidOrganized.OS30pkAntibiotics", 0.4,
        }
    },

    EasyPackingItems_misc = {
        rolls = 4,
        items = {
            "GidOrganized.OS4pkDuctTape", 4,
            "GidOrganized.10pkRopeSheetMetal", 4,
            "GidOrganized.5pkRopeSheetMetal", 4,
            "GidOrganized.10pkSheetRopeSheetMetal", 4,
            "GidOrganized.5pkSheetRopeSheetMetal", 2,
            "GidOrganized.10pkScrapMetal", 2,
            "GidOrganized.5pkScrapMetal", 2 ,
            "GidOrganized.10pkRopeMetalBar", 2,
            "GidOrganized.5pkRopeMetalBar", 4,
            "GidOrganized.10pkSheetRopeMetalBar", 3.2,
            "GidOrganized.5pkSheetRopeMetalBar", 1,
            "GidOrganized.10pkRopeMetalPipe", 1,
            "GidOrganized.5pkRopeMetalPipe", 1,
            "GidOrganized.10pkSheetRopeMetalPipe", 4,
            "GidOrganized.5pkSheetRopeMetalPipe", 4,
            "GidOrganized.10pkRopeBranch", 2,
            "GidOrganized.5pkRopeBranch", 4,
            "GidOrganized.10pkSheetRopeBranch", 2,
            "GidOrganized.5pkSheetRopeBranch", 2,
            "GidOrganized.10pkSheetRopePlank", 4,
            "GidOrganized.5pkSheetRopePlank", 4,
            "GidOrganized.10pkRopePlank", 3.2,
            "GidOrganized.5pkRopePlank", 3.2,
            "GidOrganized.10pkGarbage", 1,
            "GidOrganized.5pkGarbage", 1,
            "GidOrganized.10pkSoap", 4,
            "GidOrganized.5pkSoap", 2,
            "GidOrganized.10pkTissue", 2,
            "GidOrganized.5pkTissue", 2,
            "GidOrganized.10pkThread", 2,
            "GidOrganized.5pkThread", 2,
            "GidOrganized.10pkWire", 2,
            "GidOrganized.5pkWire", 4,
            "GidOrganized.10pkFishingLine", 1,
            "GidOrganized.5pkFishingLine", 1,
            "GidOrganized.10pkTwine", 1,
            "GidOrganized.5pkTwine", 1,
            "GidOrganized.10pkMatches", 1,
            "GidOrganized.5pkMatches", 1,
            "GidOrganized.10pkSheetMetal", 4,
            "GidOrganized.5pkSheetMetal", 4,
            "GidOrganized.10pkSheetMetalSmall", 4,
            "GidOrganized.5pkSheetMetalSmall", 3.2,
            "GidOrganized.10pkMetalBar", 3.2,
            "GidOrganized.5pkMetalBar", 1,
            "GidOrganized.10pkMetalPipe", 1,
            "GidOrganized.5pkMetalPipe", 1,
            "GidOrganized.10pkRope", 2,
            "GidOrganized.5pkRope", 2,
            "GidOrganized.10pkSheetRope", 4,
            "GidOrganized.5pkSheetRope", 4,
            "GidOrganized.10pkLighter", 2,
            "GidOrganized.5pkLighter", 2,
            "GidOrganized.10pkWoodGlue", 1,
            "GidOrganized.5pkWoodGlue", 1,
            "GidOrganized.10pkGlue", 2,
            "GidOrganized.5pkGlue", 2,
            "GidOrganized.4pkToiletPaper", 2,
            "GidOrganized.210pkFishingNet", 2,
            "GidOrganized.5pkFishingNet", 2,
            "GidOrganized.10pkBattery", 2,
            "GidOrganized.5pkBattery", 2,
            "GidOrganized.10pkElectronicsScrap", 1,
            "GidOrganized.50pkElectronicsScrap", 2,
            "GidOrganized.100pkElectronicsScrap", 1,
            "GidOrganized.10pkRag", 1,
            "GidOrganized.50pkRag", 1,
            "GidOrganized.100pkRag", 1,
            "GidOrganized.10pkDenim", 1,
            "GidOrganized.50pkDenim", 3.2,
            "GidOrganized.100pkDenim", 3.2,
            "GidOrganized.10pkLeather", 3.2,
            "GidOrganized.50pkLeather", 3.2,
            "GidOrganized.100pkLeather", 2,            
        }
    },

    EasyPackingItems_counter_cafe = {
        rolls = 4,
        items = {
            "GidOrganized.OS4pkCoffee", 2,
            "GidOrganized.OS6pkPopDiet", 2,
            "GidOrganized.OS6pkPop", 2,
            "GidOrganized.OS6pkFizz", 2,
            "GidOrganized.OS24pkWaterBottleFull", 0.4,
        }
    },

    EasyPackingItems_displaycase_cafe = {
        rolls = 4,
        items = {
            "GidOrganized.OS4pkCoffee", 2,
            "GidOrganized.OS6pkPopDiet", 2,
            "GidOrganized.OS6pkPop", 2,
            "GidOrganized.OS6pkFizz", 2,
            "GidOrganized.OS24pkWaterBottleFull", 0.4,
        }
    },

    EasyPackingItems_restaurantdisplay_cafe = {
        rolls = 4,
        items = {
            "GidOrganized.OS4pkCoffee", 2,
            "GidOrganized.OS6pkPopDiet", 2,
            "GidOrganized.OS6pkPop", 2,
            "GidOrganized.OS6pkFizz", 2,
            "GidOrganized.OS24pkWaterBottleFull", 0.4,
        }
    },
    
    EasyPackingItems_create_cafe = {
        rolls = 4,
        items = {
            "GidOrganized.OS4pkCoffee", 2,
            "GidOrganized.OS6pkPopDiet", 2,
            "GidOrganized.OS6pkPop", 2,
            "GidOrganized.OS6pkFizz", 2,
            "GidOrganized.OS24pkWaterBottleFull", 0.4,
        }
    },

    EasyPackingItems_store_counter = {
        rolls = 4,
        items = {
            "GidOrganized.OS6pkCannedSoup", 2,
            "GidOrganized.OS6pkCannedBeans", 2,
            "GidOrganized.OS6pkCannedBolognese", 2,
            "GidOrganized.OS6pkCannedCarrots", 1,
            "GidOrganized.OS6pkCannedChili", 1,
            "GidOrganized.OS6pkCannedCorn", 1,
            "GidOrganized.OS6pkCannedCornedBeef", 1,
            "GidOrganized.OS6pkCannedMushSoup", 1,
            "GidOrganized.OS6pkCannedPeas", 1,
            "GidOrganized.OS6pkCannedPotato", 1,
            "GidOrganized.OS6pkCannedTomato", 2,
            "GidOrganized.OS8pkCannedTuna", 2,
            "GidOrganized.OS4pkSardines", 2,
            "GidOrganized.OS4pkCoffee", 2,
            "GidOrganized.OS24pkWaterBottleFull", 0.4,
            "GidOrganized.6pkBeer", 0.4,
            "GidOrganized.6pkDogFood", 1,
            "GidOrganized.20pkCigarettes", 1,
        }
    },

    EasyPackingItems_store_fridge_freezer = {
        rolls = 4,
        items = {
            "GidOrganized.OS6pkPopDiet", 2,
            "GidOrganized.OS6pkPop", 2,
            "GidOrganized.OS6pkFizz", 2,
            "GidOrganized.OS24pkWaterBottleFull", 0.4,
            "GidOrganized.6pkBeerCan", 0.4,
            "GidOrganized.6pkBeer", 0.4,
            "GidOrganized.10pkWhiteWine", 2,
            "GidOrganized.5pkWhiteWine", 2,
            "GidOrganized.10pkOrangeSoda", 2,
            "GidOrganized.5pkOrangeSoda", 1,
            "GidOrganized.10pkWhiskey", 0.4,
            "GidOrganized.5pkWhiskey", 2,
            "GidOrganized.10pkRedWine", 2,
            "GidOrganized.5pkRedWine", 1,
        }
    },

    EasyPackingItems_store_metal_shelves = {
        rolls = 4,
        items = {
            "GidOrganized.OS6pkPopDiet", 2,
            "GidOrganized.OS6pkPop", 2,
            "GidOrganized.OS6pkFizz", 2,
            "GidOrganized.OS6pkCannedSoup", 2,
            "GidOrganized.OS6pkCannedBeans", 2,
            "GidOrganized.OS6pkCannedBolognese", 2,
            "GidOrganized.OS6pkCannedCarrots", 1,
            "GidOrganized.OS6pkCannedChili", 1,
            "GidOrganized.OS6pkCannedCorn", 1,
            "GidOrganized.OS6pkCannedCornedBeef", 1,
            "GidOrganized.OS6pkCannedMushSoup", 1,
            "GidOrganized.OS6pkCannedPeas", 1,
            "GidOrganized.OS6pkCannedPotato", 1,
            "GidOrganized.OS6pkCannedTomato", 2,
            "GidOrganized.OS8pkCannedTuna", 2,
            "GidOrganized.OS4pkSardines", 2,
            "GidOrganized.OS4pkCoffee", 2,
            "GidOrganized.OS24pkWaterBottleFull", 0.4,
            "GidOrganized.6pkBeerCan", 0.4,
            "GidOrganized.6pkBeer", 0.4,
            "GidOrganized.6pkDogFood", 1,
            "GidOrganized.20pkCigarettes", 1,
            "GidOrganized.10pkWhiteWine", 2,
            "GidOrganized.5pkWhiteWine", 2,
            "GidOrganized.10pkOrangeSoda", 2,
            "GidOrganized.5pkOrangeSoda", 1,
            "GidOrganized.10pkWhiskey", 0.4,
            "GidOrganized.5pkWhiskey", 2,
            "GidOrganized.10pkRedWine", 2,
            "GidOrganized.5pkRedWine", 1,
        }
    },

    EasyPackingItems_store_shelves = {
        rolls = 4,
        items = {
            "GidOrganized.OS6pkPopDiet", 2,
            "GidOrganized.OS6pkPop", 2,
            "GidOrganized.OS6pkFizz", 2,
            "GidOrganized.OS6pkCannedSoup", 2,
            "GidOrganized.OS6pkCannedBeans", 2,
            "GidOrganized.OS6pkCannedBolognese", 2,
            "GidOrganized.OS6pkCannedCarrots", 1,
            "GidOrganized.OS6pkCannedChili", 1,
            "GidOrganized.OS6pkCannedCorn", 1,
            "GidOrganized.OS6pkCannedCornedBeef", 1,
            "GidOrganized.OS6pkCannedMushSoup", 1,
            "GidOrganized.OS6pkCannedPeas", 1,
            "GidOrganized.OS6pkCannedPotato", 1,
            "GidOrganized.OS6pkCannedTomato", 2,
            "GidOrganized.OS8pkCannedTuna", 2,
            "GidOrganized.OS4pkSardines", 2,
            "GidOrganized.OS4pkCoffee", 2,
            "GidOrganized.OS24pkWaterBottleFull", 0.4,
            "GidOrganized.6pkBeerCan", 0.4,
            "GidOrganized.6pkBeer", 0.4,
            "GidOrganized.6pkDogFood", 1,
            "GidOrganized.20pkCigarettes", 1,
            "GidOrganized.10pkWhiteWine", 2,
            "GidOrganized.5pkWhiteWine", 2,
            "GidOrganized.10pkOrangeSoda", 2,
            "GidOrganized.5pkOrangeSoda", 1,
            "GidOrganized.10pkWhiskey", 0.4,
            "GidOrganized.5pkWhiskey", 2,
            "GidOrganized.10pkRedWine", 2,
            "GidOrganized.5pkRedWine", 1,
        }
    },

    EasyPackingItems_store_create = {
        rolls = 4,
        items = {
            "GidOrganized.OS6pkPopDiet", 2,
            "GidOrganized.OS6pkPop", 2,
            "GidOrganized.OS6pkFizz", 2,
            "GidOrganized.OS6pkCannedSoup", 2,
            "GidOrganized.OS6pkCannedBeans", 2,
            "GidOrganized.OS6pkCannedBolognese", 2,
            "GidOrganized.OS6pkCannedCarrots", 1,
            "GidOrganized.OS6pkCannedChili", 1,
            "GidOrganized.OS6pkCannedCorn", 1,
            "GidOrganized.OS6pkCannedCornedBeef", 1,
            "GidOrganized.OS6pkCannedMushSoup", 1,
            "GidOrganized.OS6pkCannedPeas", 1,
            "GidOrganized.OS6pkCannedPotato", 1,
            "GidOrganized.OS6pkCannedTomato", 2,
            "GidOrganized.OS8pkCannedTuna", 2,
            "GidOrganized.OS4pkSardines", 2,
            "GidOrganized.OS4pkCoffee", 2,
            "GidOrganized.OS24pkWaterBottleFull", 0.4,
            "GidOrganized.6pkBeerCan", 0.4,
            "GidOrganized.6pkBeer", 0.4,
            "GidOrganized.6pkDogFood", 1,
            "GidOrganized.20pkCigarettes", 1,
            "GidOrganized.10pkWhiteWine", 2,
            "GidOrganized.5pkWhiteWine", 2,
            "GidOrganized.10pkOrangeSoda", 2,
            "GidOrganized.5pkOrangeSoda", 1,
            "GidOrganized.10pkWhiskey", 0.4,
            "GidOrganized.5pkWhiskey", 2,
            "GidOrganized.10pkRedWine", 2,
            "GidOrganized.5pkRedWine", 1,
        },
    },
}